import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  Cat,
  CheckSquare,
  ChefHat,
  Church,
  CircleDollarSign,
  ClipboardList,
  Coffee,
  Compass,
  Dog,
  Dumbbell,
  FileText,
  Flag,
  Flower2,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  Key,
  Landmark,
  Laptop,
  LayoutGrid,
  Leaf,
  Lightbulb,
  MapPin,
  Megaphone,
  Music,
  Package,
  Paintbrush,
  Palmtree,
  PartyPopper,
  PawPrint,
  Phone,
  Pill,
  Plane,
  Receipt,
  Rocket,
  Share2,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Target,
  Tent,
  Train,
  TreePine,
  Trophy,
  Truck,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

/** Ikony dostępne w pickerze grup. */
export const GROUP_ICON_OPTIONS = [
  "Home",
  "Building2",
  "Briefcase",
  "Users",
  "Heart",
  "ShoppingCart",
  "ShoppingBag",
  "Utensils",
  "Coffee",
  "ChefHat",
  "Car",
  "Bus",
  "Train",
  "Plane",
  "Ship",
  "Truck",
  "MapPin",
  "Compass",
  "Palmtree",
  "Tent",
  "Hotel",
  "Sun",
  "Umbrella",
  "TreePine",
  "Leaf",
  "Flower2",
  "Dog",
  "Cat",
  "PawPrint",
  "Baby",
  "GraduationCap",
  "BookOpen",
  "Laptop",
  "Smartphone",
  "Calendar",
  "CheckSquare",
  "ClipboardList",
  "FileText",
  "Target",
  "Flag",
  "Trophy",
  "Dumbbell",
  "Activity",
  "HeartPulse",
  "Stethoscope",
  "Pill",
  "Banknote",
  "Wallet",
  "CircleDollarSign",
  "Receipt",
  "Store",
  "Package",
  "Hammer",
  "Wrench",
  "Paintbrush",
  "Lightbulb",
  "Zap",
  "Music",
  "Camera",
  "Gamepad2",
  "Gift",
  "Cake",
  "PartyPopper",
  "Sparkles",
  "Star",
  "Rocket",
  "Globe",
  "Landmark",
  "Church",
  "Shield",
  "Key",
  "Phone",
  "Megaphone",
  "LayoutGrid",
  "Share2",
  "Archive",
] as const;

export type GroupIconName = (typeof GROUP_ICON_OPTIONS)[number];

export const SYSTEM_GROUP_ICONS = {
  all: "LayoutGrid",
  share: "Share2",
  archive: "Archive",
} as const satisfies Record<string, GroupIconName>;

const ICON_MAP: Record<GroupIconName, LucideIcon> = {
  Home,
  Building2,
  Briefcase,
  Users,
  Heart,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  Coffee,
  ChefHat,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Truck,
  MapPin,
  Compass,
  Palmtree,
  Tent,
  Hotel,
  Sun,
  Umbrella,
  TreePine,
  Leaf,
  Flower2,
  Dog,
  Cat,
  PawPrint,
  Baby,
  GraduationCap,
  BookOpen,
  Laptop,
  Smartphone,
  Calendar,
  CheckSquare,
  ClipboardList,
  FileText,
  Target,
  Flag,
  Trophy,
  Dumbbell,
  Activity,
  HeartPulse,
  Stethoscope,
  Pill,
  Banknote,
  Wallet,
  CircleDollarSign,
  Receipt,
  Store,
  Package,
  Hammer,
  Wrench,
  Paintbrush,
  Lightbulb,
  Zap,
  Music,
  Camera,
  Gamepad2,
  Gift,
  Cake,
  PartyPopper,
  Sparkles,
  Star,
  Rocket,
  Globe,
  Landmark,
  Church,
  Shield,
  Key,
  Phone,
  Megaphone,
  LayoutGrid,
  Share2,
  Archive,
};

export function resolveGroupIcon(name?: string | null): LucideIcon {
  if (name && name in ICON_MAP) return ICON_MAP[name as GroupIconName];
  return Package;
}

/** Domyślna ikona wg nazwy lub indeksu przy tworzeniu grupy. */
export function defaultGroupIconForName(name: string, index: number): GroupIconName {
  const n = name.toLowerCase();
  if (/zakup|shop|market/.test(n)) return "ShoppingCart";
  if (/rodzin|family|dom|home/.test(n)) return "Home";
  if (/firm|biz|work|projekt|office/.test(n)) return "Briefcase";
  if (/zdrow|health|lekarz/.test(n)) return "HeartPulse";
  if (/auto|samoch/.test(n)) return "Car";
  if (/podró|travel|wakac/.test(n)) return "Plane";
  if (/szko|edu|nauka/.test(n)) return "GraduationCap";
  if (/finans|bank|pieni/.test(n)) return "Wallet";
  return GROUP_ICON_OPTIONS[index % GROUP_ICON_OPTIONS.length];
}

export function isGroupIconName(value: string): value is GroupIconName {
  return value in ICON_MAP;
}
