/**
 * Pełna inwentaryzacja mutacji synchronizowanych danych (Sync v3).
 * Status dokumentu: Implementacja nieukończona, wymagane domknięcie mutacji i testów
 * — dopóki wiersze nie mają IDB_FIRST + commitLocalMutation / commitDomainMutation.
 *
 * Wymagana kolejność (items):
 * kanoniczny snapshot → 1 txn IDB entity+operation → commit → Zustand → wakeWorker
 */

export type WriteOrder = "IDB_FIRST" | "ZUSTAND_FIRST" | "LOCAL_ONLY" | "REMOTE_APPLY";

export interface MutationInventoryRow {
  file: string;
  fn: string;
  entity: "item" | "group" | "user_tag" | "tag_assignment" | "participant" | "settings" | "ui";
  currentOrder: WriteOrder;
  usesCommitLocalMutation: boolean;
  idbFirst: boolean;
  createsOperationAtomically: boolean;
  dependsOnNotify: boolean;
  dependsOnSubscribe: boolean;
  canChangeUiBeforeDurableWrite: boolean;
  changeRequired: string;
}

export const MUTATION_INVENTORY: MutationInventoryRow[] = [
  {
    file: "src/state/store.ts",
    fn: "upsertItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "v3: persistItemViaSyncV3; v2: notify (tylko przed active)",
  },
  {
    file: "src/state/store.ts",
    fn: "patchItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "Pokrywa checklist, reminders, participants, recurrence, links/attachments, personalReminders, mark done via toggleTaskDone",
  },
  {
    file: "src/state/store.ts",
    fn: "toggleTaskDone",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "via patchItem",
  },
  {
    file: "src/state/store.ts",
    fn: "addItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "none after v3 path",
  },
  {
    file: "src/state/store.ts",
    fn: "deleteItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "tombstone via persist delete",
  },
  {
    file: "src/state/store.ts",
    fn: "duplicateItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "item + optional tag_assignment",
  },
  {
    file: "src/state/store.ts",
    fn: "pasteAt",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "none",
  },
  {
    file: "src/state/store.ts",
    fn: "commitDraft",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "none",
  },
  {
    file: "src/state/store.ts",
    fn: "dismissGroupPrompt",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "none",
  },
  {
    file: "src/state/store.ts",
    fn: "deleteGroup",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "scrub items then group delete domain op",
  },
  {
    file: "src/state/store.ts",
    fn: "deleteTag",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "scrub items then tag delete",
  },
  {
    file: "src/state/store.ts",
    fn: "setItemTagIds",
    entity: "tag_assignment",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "item tagIds + tag_assignment entity",
  },
  {
    file: "src/state/store.ts",
    fn: "addGroup/patchGroup/moveGroup",
    entity: "group",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: false,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "commitDomainMutation via persistGroupViaSyncV3",
  },
  {
    file: "src/state/store.ts",
    fn: "addTag/patchTag",
    entity: "user_tag",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: false,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "persistTagViaSyncV3",
  },
  {
    file: "src/components/item/ItemEditorPanel.tsx",
    fn: "onParticipantsChange / personalReminders / patch fields",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "wyłącznie przez patchItem store",
  },
  {
    file: "src/components/calendar/TimeGrid.tsx",
    fn: "drag resize patchItem",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "via patchItem",
  },
  {
    file: "src/hooks/useReminderScheduler.ts",
    fn: "patchItem personalReminders/reminders firedAt",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "via patchItem",
  },
  {
    file: "src/components/prompts/GroupSelectPrompt.tsx",
    fn: "patchItem groupId",
    entity: "item",
    currentOrder: "IDB_FIRST",
    usesCommitLocalMutation: true,
    idbFirst: true,
    createsOperationAtomically: true,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "via patchItem",
  },
  {
    file: "src/lib/cloud.ts",
    fn: "pullAllViaSyncV3 / mergeRemoteIntoLocal",
    entity: "item",
    currentOrder: "REMOTE_APPLY",
    usesCommitLocalMutation: false,
    idbFirst: true,
    createsOperationAtomically: false,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: false,
    changeRequired: "entity put bez op — remote apply OK",
  },
  {
    file: "src/lib/cloud.ts",
    fn: "registerLocalItemWriteHandler",
    entity: "item",
    currentOrder: "ZUSTAND_FIRST",
    usesCommitLocalMutation: false,
    idbFirst: false,
    createsOperationAtomically: false,
    dependsOnNotify: true,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: true,
    changeRequired: "TYLKO v2 gdy !active; po active no-op",
  },
  {
    file: "src/lib/syncState.ts",
    fn: "trackStoreDirty / markItemDirty / enqueueItem",
    entity: "item",
    currentOrder: "ZUSTAND_FIRST",
    usesCommitLocalMutation: false,
    idbFirst: false,
    createsOperationAtomically: false,
    dependsOnNotify: false,
    dependsOnSubscribe: true,
    canChangeUiBeforeDurableWrite: true,
    changeRequired: "zablokowane gdy shouldRegisterV2ItemWriter()===false",
  },
  {
    file: "src/state/store.ts",
    fn: "setSettings / draft / UI filters",
    entity: "settings",
    currentOrder: "LOCAL_ONLY",
    usesCommitLocalMutation: false,
    idbFirst: false,
    createsOperationAtomically: false,
    dependsOnNotify: false,
    dependsOnSubscribe: false,
    canChangeUiBeforeDurableWrite: true,
    changeRequired: "nie synchronizowane Sync v3",
  },
];

/** Alias kompatybilności. */
export const ITEM_MUTATION_INVENTORY = MUTATION_INVENTORY;

/**
 * WARIANT A — ownership writera po cutoverze (jedna domena = jeden writer):
 * - item (+ embedded participants/checklist/reminders/recurrence/attachments): Sync v3 commitLocalMutation
 * - group: Sync v3 commitDomainMutation
 * - user_tag: Sync v3 commitDomainMutation
 * - tag_assignment: Sync v3 commitDomainMutation (entityId ta:{itemId})
 * - participant-role patches (shareRole=participant): nadal w item snapshot; push specjalny w workerze
 * - v2 enqueue/orphan/pushDirty: WYŁĄCZONE gdy migrationState=active
 */
export const DOMAIN_WRITER_OWNERSHIP = {
  item: "sync_v3",
  group: "sync_v3",
  user_tag: "sync_v3",
  tag_assignment: "sync_v3",
  participant_embedded_in_item: "sync_v3_item_snapshot",
  v2_item_writer: "disabled_when_active",
} as const;
